"""Post-scout trend analysis — Ellen's primary LLM ask 2026-04-25.

After the scout collects every event, this module produces an
`analysis.md` file for the target audience: anti-corruption compliance
professionals working in corporate compliance functions.

Output structure (per Tom's direction 2026-04-28):

- Per-country sections of "trends or takeaways."
- Cap of 2-3 bullets per country, unless major changes warrant more.
- United States gets up to 5 bullets.

The file itself contains:

1. Deterministic source-data summary stats (computed in Python; always
   accurate regardless of LLM mode).
2. The prompt that would be sent to Claude (so Tom can iterate on
   prompt design without burning API spend).
3. Either a stub placeholder analysis or a real Claude analysis,
   depending on `LAWTRACKER_LLM_MODE`.
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import date, datetime
from pathlib import Path
from typing import Any

from lawtracker import llm
from lawtracker.sources import EventRecord

ANALYSIS_SYSTEM = (
    "You are an FCPA / global anti-corruption analyst writing for "
    "anti-corruption compliance professionals working inside corporate "
    "compliance functions. Read the structured event table the user "
    "provides and produce a concise markdown analysis organized by "
    "country. Be specific — name companies, industries, agencies, and "
    "amounts when the data supports it. Avoid hedging. Write for an "
    "in-house audience: emphasize what they should do, watch, or escalate."
)

ANALYSIS_USER_TEMPLATE = """\
Below is a JSON list of recent anti-corruption enforcement and policy events from \
{n_sources} sources covering the past ~24 months.

Produce a markdown analysis organized by country. The target audience is \
anti-corruption compliance professionals working inside companies.

Rules:

- **Derive each event's effective country from the event text** (title, summary, primary_actor). \
The `country` field in the JSON is a best-effort hint from the source adapter and is often the \
country of the *publisher* (e.g. a US law-firm blog covering a Brazilian enforcement action is \
tagged `US` even though the substance is Brazil). Trust the text over the field.
- **Bucket each event under the jurisdiction whose authorities brought the action**, not the \
country where the underlying conduct or bribes occurred. A US DOJ FCPA action against TIGO for \
payments in Guatemala goes under **United States** — Guatemala does *not* get its own section \
just because foreign officials were involved. Mention the foreign locus of conduct as *context \
inside the US bullet* (e.g. "DOJ resolved a $XM FCPA case against Acme involving payments to \
Guatemalan officials").
- **The exception**: when a single matter is resolved through **coordinated enforcement actions \
by multiple governments' authorities** (e.g. Petrobras / Lava Jato — DOJ + Brazilian MPF/CGU + \
Swiss OAG; Airbus — DOJ + UK SFO + French PNF), give the foreign jurisdiction its own section \
with a summary of that country's role in the resolution. The trigger is *that government's own \
action*, not US-only enforcement that happened to involve foreign conduct.
- Order sections with `## United States` first, then remaining countries by event volume \
(highest first).
- Under each country heading, write the most important **trends or takeaways** as bullets:
  - **United States: up to 5 bullets.**
  - **All other countries: 2-3 bullets**, unless there have been *major* changes in that \
jurisdiction (new statute, headline-level enforcement action, agency restructuring, etc.) — \
in which case you may exceed 3 bullets and explicitly note why.
- Each bullet should be specific: name the agency, company, statute, industry, dollar amount, \
or resolution type when the data supports it. A bullet that could apply to any jurisdiction in \
any year is not a takeaway — drop it.
- Skip a country entirely if it has fewer than 2 events AND nothing notable to say.
- If global commentary genuinely concerns no specific jurisdiction, place it under a final \
`## Cross-jurisdictional` section only if it materially adds to the country-level picture; \
otherwise drop it.

Events table (JSON):

```json
{events_json}
```
"""

STUB_ANALYSIS = """\
> _**[STUB LLM RESPONSE]** — generated by the stub client, not by Claude. \
Set `LAWTRACKER_LLM_MODE=anthropic` (or pass `--llm-mode=anthropic` to the scout) \
and install the anthropic SDK to get a real analysis. Tom is iterating on prompt \
design before turning on live API calls._

## United States
- **[STUB]** DOJ FCPA Unit continues to favor declinations under the Corporate Enforcement \
Policy when companies self-disclose; recent medical-device resolutions illustrate the pattern.
- **[STUB]** Aerospace and defense remain a concentrated risk area, with multiple DPA / NPA \
resolutions involving foreign sales-agent payments.
- **[STUB]** SEC FCPA accounting-provisions enforcement is up sharply year-over-year, driven \
by books-and-records cases against issuers with foreign subsidiaries.
- **[STUB]** DOJ pilot programs on whistleblower awards and individual accountability are \
shifting expectations for compliance program design.
- **[STUB]** Cross-border coordination with French (PNF) and Brazilian (CGU / MPF) \
authorities is producing parallel resolutions with credit-sharing arrangements.

## Chile
- **[STUB]** Fiscalía Nacional has opened multiple investigations under Ley 20.393 targeting \
mid-size construction firms; corporate liability is the operative theory.
- **[STUB]** Consejo para la Transparencia activity suggests heightened public-records \
scrutiny of municipal procurement.

## Australia
- **[STUB]** AFP foreign-bribery prosecutions remain rare in absolute terms but the \
recently-passed corporate-failure-to-prevent offense is reshaping board-level expectations.
- **[STUB]** AUSTRAC enforcement against financial institutions continues to be the more \
active enforcement channel for compliance practitioners to monitor.
"""


def build_analysis(events: list[EventRecord]) -> str:
    """Return the full analysis.md content for the current scout run."""
    stats = _deterministic_stats(events)
    user_prompt = _build_user_prompt(events)
    llm_text = llm.complete(
        system=ANALYSIS_SYSTEM,
        user=user_prompt,
        stub=STUB_ANALYSIS,
        max_tokens=2048,
    )
    return _assemble_markdown(stats, user_prompt, llm_text)


def analyze_from_jsonl(jsonl_path: Path, output_path: Path) -> int:
    """Read a scout's events.jsonl, run the LLM analysis, write the .md file.

    Pipeline split (Tom 2026-04-28): scout writes the raw outputs (xlsx /
    jsonl / summary) and stops; this is the separate step that turns them
    into analysis.md. Re-runnable while iterating on the prompt without
    re-polling adapters.

    Returns the number of events analyzed.
    """
    events: list[EventRecord] = []
    with jsonl_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            events.append(EventRecord.model_validate_json(line))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_analysis(events), encoding="utf-8")
    return len(events)


def _deterministic_stats(events: list[EventRecord]) -> dict[str, Any]:
    """Pure-Python stats. Always accurate regardless of LLM mode."""
    total = len(events)
    by_source: Counter[str] = Counter(e.source_id for e in events)
    by_country: Counter[str] = Counter(e.country or "(none)" for e in events)
    by_month: Counter[tuple[int, int]] = Counter(
        (e.event_date.year, e.event_date.month) for e in events if e.event_date
    )
    industries: Counter[str] = Counter(
        str(e.metadata["industry"])
        for e in events
        if e.metadata.get("industry")
    )
    actors: Counter[str] = Counter(e.primary_actor for e in events if e.primary_actor)
    return {
        "total": total,
        "by_source": by_source,
        "by_country": by_country,
        "by_month": by_month,
        "industries": industries,
        "actors": actors,
    }


def _build_user_prompt(events: list[EventRecord]) -> str:
    """Construct the LLM user prompt with a JSON dump of events."""
    sources = sorted({e.source_id for e in events})
    payload = [
        {
            "title": e.title,
            "source_id": e.source_id,
            "country": e.country,
            "event_date": e.event_date.isoformat() if e.event_date else None,
            "primary_actor": e.primary_actor,
            "summary": e.summary,
            "url": e.url,
            "metadata": {k: v for k, v in e.metadata.items() if not k.endswith("_es")},
        }
        for e in events
    ]
    return ANALYSIS_USER_TEMPLATE.format(
        n_sources=len(sources),
        events_json=json.dumps(payload, ensure_ascii=False, default=_json_default),
    )


def _json_default(value: Any) -> Any:
    if isinstance(value, date | datetime):
        return value.isoformat()
    raise TypeError(f"unserializable type: {type(value).__name__}")


def _assemble_markdown(
    stats: dict[str, Any],
    user_prompt: str,
    llm_text: str,
) -> str:
    lines: list[str] = []
    lines.append(f"# Anti-Corruption Enforcement Analysis — {date.today().isoformat()}")
    lines.append("")
    lines.append(
        f"_{stats['total']} events from {len(stats['by_source'])} sources. "
        f"Generated by `lawtracker scout`. LLM-generated narrative below; "
        f"deterministic counts in this header are computed directly from the data._"
    )
    lines.append("")
    lines.append("## Source counts")
    lines.append("")
    for source, n in stats["by_source"].most_common():
        lines.append(f"- `{source}`: {n}")
    lines.append("")
    lines.append("## Country counts")
    lines.append("")
    for country, n in stats["by_country"].most_common():
        lines.append(f"- {country}: {n}")
    lines.append("")
    if stats["industries"]:
        lines.append("## Industry counts (extracted)")
        lines.append("")
        for industry, n in stats["industries"].most_common(15):
            lines.append(f"- {industry}: {n}")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Narrative analysis")
    lines.append("")
    lines.append(llm_text.strip() or "_[no LLM output — mode=off]_")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<details>")
    lines.append("<summary>Prompt sent to LLM (for design iteration)</summary>")
    lines.append("")
    lines.append("**System:**")
    lines.append("")
    lines.append("```")
    lines.append(ANALYSIS_SYSTEM)
    lines.append("```")
    lines.append("")
    lines.append("**User (truncated to 8000 chars in this preview):**")
    lines.append("")
    lines.append("```")
    lines.append(user_prompt[:8000] + ("…" if len(user_prompt) > 8000 else ""))
    lines.append("```")
    lines.append("")
    lines.append("</details>")
    lines.append("")
    return "\n".join(lines)
