"""Post-scout trend analysis — Ellen's primary LLM ask 2026-04-25.

After the scout collects every event, this module produces an
`analysis.md` file for Ellen with:

1. Deterministic source-data summary stats (computed in Python; always
   accurate regardless of LLM mode).
2. The prompt that would be sent to Claude (so Tom can iterate on
   prompt design without burning API spend).
3. Either a stub placeholder analysis or a real Claude analysis,
   depending on `LAWTRACKER_LLM_MODE`.

Ellen's questions, baked into the prompt:
- Are there fewer enforcement actions against companies than the prior
  6 months?
- Are cases concentrated in a particular industry?
- What should anti-corruption compliance professionals and lawyers
  care about right now?
- What will risk and audit committee boards need to know?
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import date, datetime
from typing import Any

from lawtracker import llm
from lawtracker.sources import EventRecord

ANALYSIS_SYSTEM = (
    "You are an FCPA / global anti-corruption analyst writing for senior "
    "compliance lawyers and corporate risk-and-audit committee members. "
    "Read the structured event table the user provides and produce a "
    "concise markdown analysis. Be specific — name companies, industries, "
    "agencies, and amounts when the data supports it. Avoid hedging."
)

ANALYSIS_USER_TEMPLATE = """\
Below is a JSON list of recent anti-corruption enforcement events from {n_sources} sources \
covering the past ~24 months. Produce a markdown analysis with these sections, in order:

## Headline takeaways
3-5 bullets capturing the most important things a senior FCPA practitioner should notice now.

## Volume and trend
Are there fewer enforcement actions against companies than the prior 6 months? Compare the most \
recent 6-month window to the 6 months before it (using `event_date`). Call out where the data is \
too thin to support a confident answer.

## Industry concentration
Which industries are over-represented? Use the `industry` field where present; otherwise infer \
from titles / summaries. Name the top 3 with example cases.

## What compliance professionals and lawyers should care about right now
Specific, concrete: what guidance should they read, which case patterns matter, what is shifting \
in DOJ / SEC / cross-jurisdictional posture?

## What risk and audit committees need to know
1-3 board-level talking points. Practical, decision-oriented. No jargon.

Events table (JSON):

```json
{events_json}
```
"""

STUB_ANALYSIS = """\
> _**[STUB LLM RESPONSE]** — generated by the stub client, not by Claude. \
Set `LAWTRACKER_LLM_MODE=anthropic` (or pass `--llm-mode=anthropic` to the scout) \
and install the anthropic SDK to get a real analysis. Tom is iterating on prompt \
design before turning on live API calls._

## Headline takeaways
- **[STUB]** Recent enforcement skews toward US DOJ FCPA actions, with a notable cluster of \
medical-device and aerospace cases.
- **[STUB]** Cross-jurisdictional posture is active: French (PNF), Brazilian, and Chinese \
counterparts appear repeatedly in DOJ press releases.
- **[STUB]** Practitioner commentary (Volkov, GAB, Miller & Chevalier reviews) is focused on \
voluntary self-disclosure under the Corporate Enforcement Policy.

## Volume and trend
**[STUB]** Real analysis would compare the most recent 6 months to the prior 6 using \
`event_date`. The deterministic stats above show monthly counts per source.

## Industry concentration
**[STUB]** Top three industries (real LLM would extract from `metadata.industry` and titles): \
1. Medical devices, 2. Aerospace, 3. Financial services.

## What compliance professionals and lawyers should care about right now
**[STUB]** Real Claude output would be substantive here. Examples of what we'd expect:
- Watch for declination patterns under the Corporate Enforcement Policy.
- Industry-specific risk in cross-jurisdictional supply chains.
- New AAG / DAG speeches signaling priority shifts.

## What risk and audit committees need to know
**[STUB]** 1-3 board-level talking points would land here. Real LLM output expected to be \
short, decision-oriented, and free of jargon.
"""


def build_analysis(events: list[EventRecord]) -> str:
    """Return the full analysis.md content for the current scout run."""
    stats = _deterministic_stats(events)
    user_prompt = _build_user_prompt(events)
    llm_text = llm.complete(
        system=ANALYSIS_SYSTEM,
        user=user_prompt,
        stub=STUB_ANALYSIS,
        max_tokens=2048,
    )
    return _assemble_markdown(stats, user_prompt, llm_text)


def _deterministic_stats(events: list[EventRecord]) -> dict[str, Any]:
    """Pure-Python stats. Always accurate regardless of LLM mode."""
    total = len(events)
    by_source: Counter[str] = Counter(e.source_id for e in events)
    by_country: Counter[str] = Counter(e.country or "(none)" for e in events)
    by_month: Counter[tuple[int, int]] = Counter(
        (e.event_date.year, e.event_date.month) for e in events if e.event_date
    )
    industries: Counter[str] = Counter(
        str(e.metadata["industry"])
        for e in events
        if e.metadata.get("industry")
    )
    actors: Counter[str] = Counter(e.primary_actor for e in events if e.primary_actor)
    return {
        "total": total,
        "by_source": by_source,
        "by_country": by_country,
        "by_month": by_month,
        "industries": industries,
        "actors": actors,
    }


def _build_user_prompt(events: list[EventRecord]) -> str:
    """Construct the LLM user prompt with a JSON dump of events."""
    sources = sorted({e.source_id for e in events})
    payload = [
        {
            "title": e.title,
            "source_id": e.source_id,
            "country": e.country,
            "event_date": e.event_date.isoformat() if e.event_date else None,
            "primary_actor": e.primary_actor,
            "summary": e.summary,
            "url": e.url,
            "metadata": {k: v for k, v in e.metadata.items() if not k.endswith("_es")},
        }
        for e in events
    ]
    return ANALYSIS_USER_TEMPLATE.format(
        n_sources=len(sources),
        events_json=json.dumps(payload, ensure_ascii=False, default=_json_default),
    )


def _json_default(value: Any) -> Any:
    if isinstance(value, date | datetime):
        return value.isoformat()
    raise TypeError(f"unserializable type: {type(value).__name__}")


def _assemble_markdown(
    stats: dict[str, Any],
    user_prompt: str,
    llm_text: str,
) -> str:
    lines: list[str] = []
    lines.append(f"# Anti-Corruption Enforcement Analysis — {date.today().isoformat()}")
    lines.append("")
    lines.append(
        f"_{stats['total']} events from {len(stats['by_source'])} sources. "
        f"Generated by `lawtracker scout`. LLM-generated narrative below; "
        f"deterministic counts in this header are computed directly from the data._"
    )
    lines.append("")
    lines.append("## Source counts")
    lines.append("")
    for source, n in stats["by_source"].most_common():
        lines.append(f"- `{source}`: {n}")
    lines.append("")
    lines.append("## Country counts")
    lines.append("")
    for country, n in stats["by_country"].most_common():
        lines.append(f"- {country}: {n}")
    lines.append("")
    if stats["industries"]:
        lines.append("## Industry counts (extracted)")
        lines.append("")
        for industry, n in stats["industries"].most_common(15):
            lines.append(f"- {industry}: {n}")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Narrative analysis")
    lines.append("")
    lines.append(llm_text.strip() or "_[no LLM output — mode=off]_")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<details>")
    lines.append("<summary>Prompt sent to LLM (for design iteration)</summary>")
    lines.append("")
    lines.append("**System:**")
    lines.append("")
    lines.append("```")
    lines.append(ANALYSIS_SYSTEM)
    lines.append("```")
    lines.append("")
    lines.append("**User (truncated to 2000 chars in this preview):**")
    lines.append("")
    lines.append("```")
    lines.append(user_prompt[:2000] + ("…" if len(user_prompt) > 2000 else ""))
    lines.append("```")
    lines.append("")
    lines.append("</details>")
    lines.append("")
    return "\n".join(lines)
